[build-system]
requires = [
  "scikit-build-core>=0.8.0",
  "pybind11",
  "setuptools",
  "wheel"
]
build-backend = "scikit_build_core.build"

[project]
name = "pyfade"
version = "0.1.0"
description = "Matrix profile calculation module"
authors = [{ name = "Heitor Lopes", email = "hnlopes@unicamp.br" }]
requires-python = ">=3.8"

[tool.scikit-build]
wheel.packages = ["src/pyfade"]

