[build-system]
requires = [
  "scikit-build-core>=0.10",
  "pybind11>=2.12"
]
build-backend = "scikit_build_core.build"

[project]
name = "pyfade-esp"
version = "1.0.0"
description = "Matrix profile calculation module"
authors = [{ name = "Heitor Lopes", email = "hnlopes@unicamp.br" }]
requires-python = ">=3.8"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "pmdarima",
    "PyWavelets"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[tool.scikit-build]
wheel.packages = ["src/pyfade"]
sdist.include = ["pyfade/**"]


[tool.scikit-build.cmake]
args = []
build-type = "Release"

[tool.scikit-build.build]
verbose = false